version: '3.8'

services:
  activity-ranking-api:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: activity-ranking-api
    environment:
      PORT: 8081
      OPEN_METEO_WEATHER_HOST: https://api.open-meteo.com
      OPEN_METEO_MARINE_HOST: https://marine-api.open-meteo.com/
      THRESHOLD_TEMPERATURE_LOW_C: -5
      THRESHOLD_TEMPERATURE_HIGH_C: 25
      THRESHOLD_PRECIPITATION_MM: 10
      THRESHOLD_WINDSPEED_KMH: 45
      THRESHOLD_SNOWFALL_CM: 5
      THRESHOLD_SUNSHINE_DURATION_SEC: 28800 # 8 hours
      THRESHOLD_LOW_ELEVATION_M: 10
      THRESHOLD_HIGH_ELEVATION_M: 1500
    ports:
      - "8081:8081"

  weather-matcher-ui:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_OPEN_METEO_API_HOST: https://geocoding-api.open-meteo.com
    container_name: weather-matcher-ui
    environment:
      ACTIVITY_RANKING_API_HOST: http://activity-ranking-api:8081
      TIMEFRAME_DAYS: 7
    ports:
      - "3000:3000"
