version: '3.8'

services:
  activity-ranking-api:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: activity-ranking-api
    environment:
      PORT: 8081
      OPEN_METEO_WEATHER_HOST: https://api.open-meteo.com
      OPEN_METEO_MARINE_HOST: https://marine-api.open-meteo.com/
    ports:
      - "8081:8081"

  weather-matcher-ui:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_OPEN_METEO_API_HOST: https://geocoding-api.open-meteo.com
    container_name: weather-matcher-ui
    environment:
      ACTIVITY_RANKING_API_HOST: http://activity-ranking-api:8081
    ports:
      - "3000:3000"
